sudo: required
dist: trusty
language: node_js
node_js:
- 6.14.1
addons:
before_script:
- npm install -g mocha
- npm install
script: npm run coveralls && npm run test && npm run ftest && npm run build
