version: 0.1
phases:
  install:
    commands:
      - echo Installing dependencies
      - npm install -g mocha
      - echo Creating deploy package
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket midwest-hackathon
                                   --output-template-file outputSamTemplate.yaml
  build:
    commands:
      - echo Running tests
      - npm run test
      - npm run ftest
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
